FORMAT: 1A
HOST: http://aware-unit.account.service/

# Account service

Account service

# Group Account

## Accounts Collection [/accounts]

### List All Accounts [GET]

+ Response 200 (application/json)

        [
        ]

### Create a New Account [POST]

+ Request (application/json)


+ Response 201 (application/json)

    + Headers


    + Body
